name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:
  PreparacaoArtefato:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Criando arquivo .env 
        run: mv .env.example .env

      - name: Preparando artefato
        run: |
          mkdir -p artifact
          rsync -a --exclude='artifact' --exclude='.git' --exclude='.github' ./ ./artifact/

      - name: Salvando artefato
        uses: actions/upload-artifact@v4
        with:
          name: audittei-api
          path: ./artifact

  HML:
    runs-on: ubuntu-latest
    environment:
        name: Staging
        url: ${{ vars.BASE_URL }}
    needs: PreparacaoArtefato
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: audittei-api
          path: ./artifact

      - name: Instalar GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Obter próxima versão
        id: get_next_version
        run: |
          gitversion gitversion.yml /outputformat json > gitversion.json
          echo "::set-output name=next_version::$(jq -r '.NextVersion' gitversion.json)"

      - name: Definindo versão
        run: echo "NEXT_VERSION=${{ steps.get_next_version.outputs.next_version }}" >> $GITHUB_ENV
  
      - name: Definindo Variáveis de ambiente
        env:
            APP_VERSION: ${{ env.APP_VERSION }}
        run: |
          sed -i "s/{{ APP_NAME }}/${{ vars.APP_NAME }}/g" ./artifact/.env
          sed -i "s/{{ APP_URL }}/${{ secrets.APP_URL }}/g" ./artifact/.env
          sed -i "s/{{ APP_VERSION }}/${{ env.APP_VERSION }}/g" ./artifact/.env
          sed -i "s/{{ ENVIRONMENT }}/${{ vars.ENVIRONMENT }}/g" ./artifact/.env
          sed -i "s/{{ DB_HOST }}/${{ secrets.DB_HOST }}/g" ./artifact/.env
          sed -i "s/{{ DB_DATABASE }}/${{ secrets.DB_DATABASE }}/g" ./artifact/.env
          sed -i "s/{{ DB_USERNAME }}/${{ secrets.DB_USERNAME }}/g" ./artifact/.env
          sed -i "s/{{ DB_PASSWORD }}/${{ secrets.DB_PASSWORD }}/g" ./artifact/.env
          sed -i "s/{{ MAIL_HOST }}/${{ secrets.MAIL_HOST }}/g" ./artifact/.env
          sed -i "s/{{ MAIL_PORT }}/${{ secrets.MAIL_PORT }}/g" ./artifact/.env
          sed -i "s/{{ MAIL_USERNAME }}/${{ secrets.MAIL_USERNAME }}/g" ./artifact/.env
          sed -i "s/{{ MAIL_PASSWORD }}/${{ secrets.MAIL_PASSWORD }}/g" ./artifact/.env
          sed -i "s/{{ MAIL_FROM_ADDRESS }}/${{ secrets.MAIL_FROM_ADDRESS }}/g" ./artifact/.env
          sed -i "s/{{ CNPJ_API_KEY }}/${{ secrets.CNPJ_API_KEY }}/g" ./artifact/.env
      
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          SOURCE: "artifact/"
          TARGET: ${{ vars.TARGET }}