name: Deploy via FTP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validação de dependências
      run: composer validate --strict

    - name: Criando arquivo .env 
      run: mv .env.example .env

    - name: Replace variables in .env file
      env:
        SECRET_ONE: ${{ secrets.APP_URL }}
      run: |
        env_file=".env"
        if [ -f "$env_file" ]; then
          while IFS= read -r line; do
            if [[ $line =~ \{\{\ ([A-Z_]+)\ \}\} ]]; then
              var_name=${BASH_REMATCH[1]}
              secret_value=${!var_name}
              if [ -n "$secret_value" ]; then
                sed -i "s/{{ ${var_name} }}/$secret_value/g" "$env_file"
              fi
            fi
          done < "$env_file"
        fi
        
    - name: Trocando versão do PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    - name: Instalação de dependências
      run: composer install --optimize-autoloader --no-dev

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: /
        server-dir: ./    