name: Deploy via FTP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validação de dependências
      run: composer validate -strict

    - name: Criando arquivo .env 
      run: mv .env.example .env
    
    - name: Definir as variáveis de ambiente da aplicação
      uses: richardrigutins/replace-in-files@v2
      with:
        files: '.env'
        search-text: '{0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, {9}'
        replacement-text: |
                      ${{ secrets.APP_URL }}, 
                      ${{ secrets.DB_HOST }}, 
                      ${{ secrets.DB_DATABASE }}, 
                      ${{ secrets.DB_USERNAME }}, 
                      ${{ secrets.DB_PASSWORD }},
                      ${{ secrets.MAIL_HOST }},
                      ${{ secrets.MAIL_PORT }},
                      ${{ secrets.MAIL_USERNAME }},
                      ${{ secrets.MAIL_PASSWORD }},
                      ${{ secrets.MAIL_FROM_ADDRESS }}

    - name: Install dependencies
      run: composer install --optimize-autoloader --no-dev

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: /
        server-dir: ./    