name: Instalar Aplicação

on:
  workflow_dispatch:

jobs:
  PreparacaoArtefato:
    runs-on: ubuntu-latest
    environment:
        name: Staging
        url: ${{ vars.BASE_URL }}
    steps:
      - name: Instalação da aplicação
        uses: nekiro/ssh-job@main
        with:
            host: ${{ vars.REMOTE_HOST }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            user: ${{ vars.REMOTE_USER }}
            command: |
                composer install --no-dev --no-progress -a
                php artisan optimize
                chown -R www-data:www-data .
                php artisan migrate
