name: Instalar Aplicação

on:
  workflow_dispatch:

jobs:
  PreparacaoArtefato:
    runs-on: ubuntu-latest
    environment:
        name: Staging
        url: ${{ vars.BASE_URL }}
    steps:
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ vars.REMOTE_HOST }}
            username: ${{ vars.REMOTE_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            port: 22
            script: composer --version
